version: '3.8'

services:
  nacos:
    image: nacos/nacos-server:v3.1.0
    container_name: nacos-server
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    volumes:
      - nacos-data:/home/nacos/data
    depends_on:
      - mysql
    networks:
      - basebackend-network

  mysql:
    image: mysql:8.0
    container_name: nacos-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nacos
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=nacos
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-nacos.sql:/docker-entrypoint-initdb.d/init-nacos.sql
    networks:
      - basebackend-network

volumes:
  nacos-data:
  mysql-data:

networks:
  basebackend-network:
    driver: bridge
