version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: basebackend-rabbitmq
    hostname: basebackend-rabbitmq
    ports:
      - "5672:5672"     # AMQP端口
      - "15672:15672"   # 管理界面端口
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: basebackend
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    networks:
      - basebackend-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq-data:
    driver: local

networks:
  basebackend-network:
    driver: bridge
