# 数据库读写分离配置示例
# 使用ShardingSphere实现主从自动切换、负载均衡、延迟检测

spring:
  shardingsphere:
    # 数据源配置
    datasource:
      names: master,slave1,slave2

      # 主库配置
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/basebackend?useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: ${MYSQL_PASSWORD:root123}
        # Druid连接池配置
        druid:
          initial-size: 5
          min-idle: 5
          max-active: 20
          max-wait: 60000
          test-while-idle: true
          validation-query: SELECT 1

      # 从库1配置
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/basebackend?useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: ${MYSQL_PASSWORD:root123}
        druid:
          initial-size: 5
          min-idle: 5
          max-active: 20
          test-while-idle: true
          validation-query: SELECT 1

      # 从库2配置
      slave2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3308/basebackend?useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: ${MYSQL_PASSWORD:root123}
        druid:
          initial-size: 5
          min-idle: 5
          max-active: 20
          test-while-idle: true
          validation-query: SELECT 1

    # 读写分离规则
    rules:
      readwrite-splitting:
        data-sources:
          basebackend:
            # 静态读写分离策略
            static-strategy:
              write-data-source-name: master
              read-data-source-names:
                - slave1
                - slave2
            # 负载均衡算法
            load-balancer-name: weighted

        # 负载均衡器配置
        load-balancers:
          # 加权负载均衡（从库权重可不同）
          weighted:
            type: WEIGHT
            props:
              slave1: 1  # 权重1
              slave2: 2  # 权重2（性能更好的机器可设置更高权重）

    # ShardingSphere属性配置
    props:
      # 打印SQL
      sql-show: true
      # 允许范围查询
      sql-simple: false

# 读写分离监控配置
database:
  readwrite-split:
    # 是否启用读写分离
    enabled: true
    # 主从延迟检测
    lag-detection:
      enabled: true
      threshold-seconds: 10  # 延迟超过10秒降级到主库
      check-interval: 5000   # 每5秒检查一次
    # 从库降级策略
    degradation:
      enabled: true
      max-retries: 3  # 从库连接失败3次后降级到主库
