-- =====================================================
-- BaseBackend Scheduler - Camunda 工作流初始化脚本
-- 版本: 2.0
-- 描述: 创建 Camunda 工作流引擎所需的数据库表
-- 依赖: 无
-- =====================================================

-- Camunda 7.x 默认表结构
-- 这些是 Camunda 工作流引擎的核心表

-- 1. 流程定义表 (ACT_RE_PROCDEF)
-- 存储已部署的流程定义信息
CREATE TABLE IF NOT EXISTS ACT_RE_PROCDEF (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INTEGER,
    CATEGORY_ VARCHAR(255),
    NAME_ VARCHAR(255),
    KEY_ VARCHAR(255) NOT NULL,
    VERSION_ INTEGER NOT NULL,
    DEPLOYMENT_ID_ VARCHAR(64),
    RESOURCE_NAME_ VARCHAR(255),
    DGRM_RESOURCE_NAME_ VARCHAR(255),
    DESCRIPTION_ VARCHAR(4000),
    HAS_START_FORM_KEY_ BOOLEAN DEFAULT FALSE,
    HAS_START_FORM_KEY_IN_METADATA_ BOOLEAN DEFAULT FALSE,
    SUSPENSION_STATE_ INTEGER,
    VERSION_TAG_ VARCHAR(64),
    HISTORIC_VARIABLE_STORAGE_TYPE_ VARCHAR(64),
    STARTABLE_ BOOLEAN DEFAULT TRUE,
    TENANT_ID_ VARCHAR(255),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. 流程实例表 (ACT_RU_EXECUTION)
-- 存储正在执行的流程实例
CREATE TABLE IF NOT EXISTS ACT_RU_EXECUTION (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INTEGER,
    ROOT_PROC_INST_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    BUSINESS_KEY_ VARCHAR(255),
    PARENT_ID_ VARCHAR(64),
    SUPER_EXEC_ VARCHAR(64),
    SUPER_CASE_EXEC_ VARCHAR(64),
    CASE_INST_ID_ VARCHAR(64),
    ACT_ID_ VARCHAR(255),
    ACT_INST_ID_ VARCHAR(255),
    VARIABLES_ LONGBLOB,
    SUSPENSION_STATE_ INTEGER,
    CACHED_ENT_STATE_ INTEGER,
    TENANT_ID_ VARCHAR(255),
    PRIMARY KEY (ID_),
    UNIQUE KEY ACT_UNIQ_HST_BUS (HISTORIC_VARIABLE),
    UNIQUE KEY ACT_UNIQ_HST_BUS (BUSINESS_KEY_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. 任务表 (ACT_RU_TASK)
-- 存储待办任务信息
CREATE TABLE IF NOT EXISTS ACT_RU_TASK (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INTEGER,
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    CASE_EXECUTION_ID_ VARCHAR(64),
    CASE_INST_ID_ VARCHAR(64),
    CASE_DEF_ID_ VARCHAR(64),
    CREATE_TIME_ DATETIME(3),
    CLAIM_TIME_ DATETIME(3),
    NAME_ VARCHAR(255),
    KEY_ VARCHAR(255),
    PARENT_TASK_ID_ VARCHAR(64),
    DESCRIPTION_ VARCHAR(4000),
    OWNER_ VARCHAR(255),
    ASSIGNEE_ VARCHAR(255),
    DELEGATION_ VARCHAR(64),
    PRIORITY_ INTEGER DEFAULT 50,
    DUE_DATE_ DATETIME(3),
    CATEGORY_ VARCHAR(255),
    FORM_KEY_ VARCHAR(255),
    CAMUNDA_FORM_REF_ VARCHAR(255),
    FOLLOW_UP_DATE_ DATETIME(3),
    CASE_INSTANCE_ID_ VARCHAR(64),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. 变量表 (ACT_RU_VARIABLE)
-- 存储流程变量
CREATE TABLE IF NOT EXISTS ACT_RU_VARIABLE (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INTEGER,
    TYPE_ VARCHAR(255) NOT NULL,
    NAME_ VARCHAR(255) NOT NULL,
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    CASE_EXECUTION_ID_ VARCHAR(64),
    CASE_INST_ID_ VARCHAR(64),
    TASK_ID_ VARCHAR(64),
    BYTES_ LONGBLOB,
    DOUBLE_ DOUBLE,
    LONG_ BIGINT,
    TEXT_ VARCHAR(4000),
    TEXT2_ VARCHAR(4000),
    VAR_SCOPE_ VARCHAR(64),
    SUB_SCOPE_ID_ VARCHAR(64),
    PRIMARY KEY (ID_),
    UNIQUE KEY ACT_UNIQ_VAR_EXEC (VAR_SCOPE_, NAME_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. 身份关联表 (ACT_RU_IDENTITYLINK)
-- 存储任务的参与人信息
CREATE TABLE IF NOT EXISTS ACT_RU_IDENTITYLINK (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INTEGER,
    GROUP_ID_ VARCHAR(255),
    TYPE_ VARCHAR(255),
    USER_ID_ VARCHAR(255),
    TASK_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    SCOPE_ID_ VARCHAR(64),
    SCOPE_TYPE_ VARCHAR(255),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. 事件订阅表 (ACT_RU_EVENT_SUBSCRIPTION)
-- 存储事件订阅信息
CREATE TABLE IF NOT EXISTS ACT_RU_EVENT_SUBSCRIPTION (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INTEGER,
    EVENT_TYPE_ VARCHAR(255) NOT NULL,
    EVENT_NAME_ VARCHAR(255),
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    ACTIVITY_ID_ VARCHAR(255),
    CONFIGURATION_ VARCHAR(255),
    CREATED_ DATETIME(3) NOT NULL,
    TENANT_ID_ VARCHAR(255),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. 作业表 (ACT_RU_JOB)
-- 存储异步作业信息
CREATE TABLE IF NOT EXISTS ACT_RU_JOB (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INTEGER,
    TYPE_ VARCHAR(255) NOT NULL,
    LOCK_EXP_TIME_ DATETIME(3),
    LOCK_OWNER_ VARCHAR(255),
    EXCLUSIVE_ BOOLEAN,
    RETRIES_ INTEGER DEFAULT 3,
    EXECUTION_ID_ VARCHAR(64),
    PROCESS_INSTANCE_ID_ VARCHAR(64),
    PROCESS_DEF_ID_ VARCHAR(64),
    HANDLER_TYPE_ VARCHAR(255),
    HANDLER_CFG_ VARCHAR(4000),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. 作业定义表 (ACT_RU_JOBDEF)
-- 存储作业定义
CREATE TABLE IF NOT EXISTS ACT_RU_JOBDEF (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INTEGER,
    TYPE_ VARCHAR(255) NOT NULL,
    JOB_CONFIGURATION_ID_ VARCHAR(255),
    PROCESS_DEF_ID_ VARCHAR(64),
    PROCESS_DEF_KEY_ VARCHAR(255),
    ACT_ID_ VARCHAR(255),
    JOB_PRIORITY_ BIGINT,
    TENANT_ID_ VARCHAR(255),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 9. 历史流程实例表 (ACT_HI_PROCINST)
-- 存储已结束的流程实例历史
CREATE TABLE IF NOT EXISTS ACT_HI_PROCINST (
    ID_ VARCHAR(64) NOT NULL,
    PROC_INST_ID_ VARCHAR(64) NOT NULL,
    BUSINESS_KEY_ VARCHAR(255),
    PROC_DEF_ID_ VARCHAR(64) NOT NULL,
    START_TIME_ DATETIME(3) NOT NULL,
    END_TIME_ DATETIME(3),
    DURATION_ BIGINT,
    START_USER_ID_ VARCHAR(255),
    START_ACT_ID_ VARCHAR(255),
    END_ACT_ID_ VARCHAR(255),
    SUPER_PROCESS_INSTANCE_ID_ VARCHAR(64),
    ROOT_PROC_INST_ID_ VARCHAR(64),
    SUPER_CASE_INSTANCE_ID_ VARCHAR(64),
    CASE_INST_ID_ VARCHAR(64),
    DELETE_REASON_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(255),
    STATE_ VARCHAR(255),
    PRIMARY KEY (ID_),
    UNIQUE KEY ACT_UNIQ_HI_BUS (BUSINESS_KEY_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 10. 历史任务实例表 (ACT_HI_TASKINST)
-- 存储已完成的历史任务
CREATE TABLE IF NOT EXISTS ACT_HI_TASKINST (
    ID_ VARCHAR(64) NOT NULL,
    PROC_DEF_ID_ VARCHAR(64),
    TASK_DEF_KEY_ VARCHAR(255),
    PROC_INST_ID_ VARCHAR(64),
    EXECUTION_ID_ VARCHAR(64),
    CASE_INST_ID_ VARCHAR(64),
    CASE_EXECUTION_ID_ VARCHAR(64),
    ACT_INST_ID_ VARCHAR(255),
    NAME_ VARCHAR(255),
    PARENT_TASK_ID_ VARCHAR(64),
    DESCRIPTION_ VARCHAR(4000),
    OWNER_ VARCHAR(255),
    ASSIGNEE_ VARCHAR(255),
    DELETE_REASON_ VARCHAR(4000),
    PRIORITY_ INTEGER,
    DUE_DATE_ DATETIME(3),
    CREATE_TIME_ DATETIME(3) NOT NULL,
    COMPLETION_TIME_ DATETIME(3),
    CATEGORY_ VARCHAR(255),
    FORM_KEY_ VARCHAR(255),
    CAMUNDA_FORM_REF_ VARCHAR(255),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 11. 历史变量实例表 (ACT_HI_VARINST)
-- 存储历史变量
CREATE TABLE IF NOT EXISTS ACT_HI_VARINST (
    ID_ VARCHAR(64) NOT NULL,
    PROC_INST_ID_ VARCHAR(64),
    EXECUTION_ID_ VARCHAR(64),
    TASK_ID_ VARCHAR(64),
    NAME_ VARCHAR(255) NOT NULL,
    VAR_TYPE_ VARCHAR(255),
    REV_ INTEGER,
    BYTES_ LONGBLOB,
    DOUBLE_ DOUBLE,
    LONG_ BIGINT,
    TEXT_ VARCHAR(4000),
    TEXT2_ VARCHAR(4000),
    CREATE_TIME_ DATETIME(3) NOT NULL,
    CREATED_ VARCHAR(255),
    LAST_UPDATED_TIME_ DATETIME(3) NOT NULL,
    LAST_UPDATED_ VARCHAR(255),
    PRIMARY KEY (ID_),
    UNIQUE KEY ACT_UNIQ_HI_VARINST (PROC_INST_ID_, NAME_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 12. 历史活动实例表 (ACT_HI_ACTINST)
-- 存储历史活动实例
CREATE TABLE IF NOT EXISTS ACT_HI_ACTINST (
    ID_ VARCHAR(64) NOT NULL,
    PROC_DEF_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    EXECUTION_ID_ VARCHAR(64),
    ACT_ID_ VARCHAR(255) NOT NULL,
    TASK_ID_ VARCHAR(64),
    CALL_PROC_INST_ID_ VARCHAR(64),
    CALL_CASE_INST_ID_ VARCHAR(64),
    ACT_NAME_ VARCHAR(255),
    ACT_TYPE_ VARCHAR(255) NOT NULL,
    ASSIGNEE_ VARCHAR(255),
    START_TIME_ DATETIME(3) NOT NULL,
    END_TIME_ DATETIME(3),
    DURATION_ BIGINT,
    ACT_INST_STATE_ INTEGER,
    CANCELLED_ BOOLEAN,
    CAMUNDA_FORM_REF_ VARCHAR(255),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 13. 历史评论表 (ACT_HI_COMMENT)
-- 存储任务和流程的评论
CREATE TABLE IF NOT EXISTS ACT_HI_COMMENT (
    ID_ VARCHAR(64) NOT NULL,
    TYPE_ VARCHAR(255),
    TIME_ DATETIME(3) NOT NULL,
    USER_ID_ VARCHAR(255),
    TASK_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    ACTION_ VARCHAR(255),
    MESSAGE_ VARCHAR(4000),
    FULL_MSG_ LONGBLOB,
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 14. 历史附件表 (ACT_HI_ATTACHMENT)
-- 存储任务和流程的附件
CREATE TABLE IF NOT EXISTS ACT_HI_ATTACHMENT (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INTEGER,
    USER_ID_ VARCHAR(255),
    NAME_ VARCHAR(255),
    DESCRIPTION_ VARCHAR(255),
    TYPE_ VARCHAR(255),
    TASK_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    CONTENT_ID_ VARCHAR(64),
    TIME_ DATETIME(3),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 15. 用户操作日志表 (ACT_HI_OP_LOG)
-- 存储用户操作历史
CREATE TABLE IF NOT EXISTS ACT_HI_OP_LOG (
    ID_ VARCHAR(64) NOT NULL,
    TIMESTAMP_ DATETIME(3) NOT NULL,
    TYPE_ VARCHAR(255),
    OP_TYPE_ VARCHAR(255),
    ENTITY_TYPE_ VARCHAR(255),
    ENTITY_ID_ VARCHAR(64),
    PROPERTY_ VARCHAR(255),
    NEW_VALUE_ VARCHAR(4000),
    ORG_VALUE_ VARCHAR(4000),
    PROC_DEF_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    EXECUTION_ID_ VARCHAR(64),
    TASK_ID_ VARCHAR(64),
    EXTERNAL_TODO_ID_ VARCHAR(255),
    APP_VERSION_ VARCHAR(255),
    USER_ID_ VARCHAR(255),
    CHANGED_BY_PROCESS_ VARCHAR(255),
    REMOTE_ADDRESS_ VARCHAR(255),
    COMMENT_ VARCHAR(4000),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 16. 部署表 (ACT_RE_DEPLOYMENT)
-- 存储部署信息
CREATE TABLE IF NOT EXISTS ACT_RE_DEPLOYMENT (
    ID_ VARCHAR(64) NOT NULL,
    NAME_ VARCHAR(255),
    DEPLOY_TIME_ DATETIME(3),
    SOURCE_ VARCHAR(255),
    TENANT_ID_ VARCHAR(255),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 17. 资源表 (ACT_GE_BYTEARRAY)
-- 存储部署的资源文件
CREATE TABLE IF NOT EXISTS ACT_GE_BYTEARRAY (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INTEGER,
    NAME_ VARCHAR(255),
    DEPLOYMENT_ID_ VARCHAR(64),
    BYTES_ LONGBLOB,
    GENERATED_ BOOLEAN,
    TENANT_ID_ VARCHAR(255),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 18. 属性表 (ACT_GE_PROPERTY)
-- 存储引擎属性
CREATE TABLE IF NOT EXISTS ACT_GE_PROPERTY (
    NAME_ VARCHAR(64) NOT NULL,
    VALUE_ VARCHAR(300),
    REV_ INTEGER,
    PRIMARY KEY (NAME_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 19. 用户表 (ACT_ID_USER)
-- 存储用户信息
CREATE TABLE IF NOT EXISTS ACT_ID_USER (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INTEGER,
    FIRST_ VARCHAR(255),
    LAST_ VARCHAR(255),
    DISPLAY_NAME_ VARCHAR(255),
    EMAIL_ VARCHAR(255),
    PWD_ VARCHAR(255),
    PICTURE_ID_ VARCHAR(64),
    TENANT_ID_ VARCHAR(255),
    LOCKED_ BOOLEAN,
    PASSWORD_HISTORY_ LONGBLOB,
    PASSWORD_UPDATE_DATE_ DATETIME(3),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 20. 组表 (ACT_ID_GROUP)
-- 存储用户组信息
CREATE TABLE IF NOT EXISTS ACT_ID_GROUP (
    ID_ VARCHAR(64) NOT NULL,
    REV_ INTEGER,
    NAME_ VARCHAR(255),
    TYPE_ VARCHAR(255),
    TENANT_ID_ VARCHAR(255),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 21. 用户与组关系表 (ACT_ID_MEMBERSHIP)
-- 存储用户与组的关系
CREATE TABLE IF NOT EXISTS ACT_ID_MEMBERSHIP (
    USER_ID_ VARCHAR(64) NOT NULL,
    GROUP_ID_ VARCHAR(64) NOT NULL,
    PRIMARY KEY (USER_ID_, GROUP_ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 22. 用户信息表 (ACT_ID_INFO)
-- 存储用户详细信息
CREATE TABLE IF NOT EXISTS ACT_ID_INFO (
    ID_ VARCHAR(64) NOT NULL,
    USER_ID_ VARCHAR(64),
    TYPE_ VARCHAR(64),
    KEY_ VARCHAR(255),
    VALUE_ VARCHAR(255),
    PASSWORD_ LONGBLOB,
    PARENT_ID_ VARCHAR(64),
    PRIMARY KEY (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 初始化引擎属性
INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('schema.version', '7.21.0', 1);
INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('schema.history', 'create(7.21.0)', 1);
INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('next.dbid', '1', 1);
INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('identity.使用时初始化标识', 'true', 1);
INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('isInit.histogram', 'false', 1);
